version: '2'

services:
  dcc-dashboard-service:
    environment:
      ES_SERVICE: "elasticsearch1"
      ES_PORT: "9200"
      ES_PROTOCOL: "http"
      ES_FILE_INDEX: "fb_index"
      ES_DONOR_INDEX: "analysis_index"
    build: .
    ports:
      - "80"
      - "443"
    networks:
      - esnet
    ports:
      - "9200"
    restart: always
  elasticsearch1:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.3
    container_name: "elasticsearch1"
    environment:
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
    ports:
       - "9200:9200"
       - "9300:9300"
    networks:
      - esnet
    restart: always

networks:
  esnet:
    driver: bridge
